name: CI

on:
  push:
    branches: ["master", "upgrade/**"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
          cache-version: 0
      - name: Build with Jekyll
        run: bundle exec jekyll build --trace --strict_front_matter
        env:
          JEKYLL_ENV: production
      - name: Check generated HTML
        run: bundle exec htmlproofer _site --disable-external
